In [1]:
from openptv_python.calibration import Exterior
import numpy as np


In [2]:
def rotation_matrix(phi, kappa, omega) -> np.ndarray:
    """Rotates the Dmatrix of Exterior using three angles of the camera.

    Args:
    ----
        exterior: The Exterior object.

    Returns:
    -------
        The modified Exterior object.
    """
    cp = np.cos(phi)
    sp = np.sin(phi)
    co = np.cos(omega)
    so = np.sin(omega)
    ck = np.cos(kappa)
    sk = np.sin(kappa)

    dm = np.zeros((3, 3), dtype=np.float64)
    dm[0, 0] = cp * ck
    dm[0, 1] = -cp * sk
    dm[0, 2] = sp
    dm[1, 0] = co * sk + so * sp * ck
    dm[1, 1] = co * ck - so * sp * sk
    dm[1, 2] = -so * cp
    dm[2, 0] = so * sk - co * sp * ck
    dm[2, 1] = so * ck + co * sp * sk
    dm[2, 2] = co * cp
    
    return dm


In [3]:

def test_rotation_matrix():
    # Known inputs
    phi = 0.5
    omega = 0.3
    kappa = 0.2

    # Expected output (previously obtained or calculated manually)
    expected_matrix = np.array([[0.83838664, -0.25934338,  0.47942554],
                                [ 0.38062256,  0.90814591, -0.17434874],
                                [-0.39017215,  0.32865183,  0.86008934]])

    # Call the rotation_matrix function
    result = rotation_matrix(phi, omega, kappa)
    print(result)

    # Compare the result with the expected output
    assert np.allclose(result, expected_matrix)

test_rotation_matrix()


[[ 0.83838664 -0.25934338  0.47942554]
 [ 0.38062256  0.90814591 -0.17434874]
 [-0.39017215  0.32865183  0.86008934]]
