In [5]:
import numpy as np
from openptv_python.lsqadj import atl  # Import the atl function from your module

def test_full_matrix_vector_multiplication():
    # Test when n equals n_large
    n = 3
    n_large = 3
    m = 3  # Match the number of columns in a with rows in b
    u = np.zeros((n, 1))
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1], [2], [3]])
    expected_u = np.dot(a.T, b)
    atl(u, a, b, m, n, n_large)
    print(u)
    assert np.array_equal(u, expected_u)

# def test_sub_matrix_vector_multiplication():
#     # Test when n is less than n_large
#     n = 2
#     n_large = 3
#     m = 4  # Match the number of columns in a with rows in b
#     u = np.zeros((n, 1))
#     a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
#     b = np.array([[1], [2], [3], [4]])
#     expected_u = np.dot(a.T[:, :n], b)
#     atl(u, a, b, m, n, n_large)
#     print(u, expected_u)
#     assert np.array_equal(u, expected_u)

def test_valid_matrix_vector_multiplication():
    # Test with valid dimensions
    n = 3
    n_large = 3
    m = 4  # Match the number of rows in a with rows in b
    u = np.zeros((n, 1))
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
    b = np.array([[1], [2], [3], [4]])
    expected_u = np.dot(a.T, b)
    atl(u, a, b, m, n, n_large)
    print(u)
    assert np.array_equal(u, expected_u)

def test_zero_input():
    # Test with all zero input
    n = 3
    n_large = 3
    m = 3  # Match the number of columns in a with rows in b
    u = np.zeros((n, 1))
    a = np.zeros((m, n_large))
    b = np.zeros((m, 1))
    atl(u, a, b, m, n, n_large)
    print(u)
    assert np.array_equal(u, np.zeros((n, 1)))

In [6]:
test_full_matrix_vector_multiplication()

[[30.]
 [36.]
 [42.]]


In [7]:
test_valid_matrix_vector_multiplication()

[[70.]
 [80.]
 [90.]]


In [8]:
test_zero_input()

[[0.]
 [0.]
 [0.]]
